INSERT INTO ER_CAMPI (I_PK_CAMPO, I_FK_TABELLA, A_NOME_CAMPO, A_DESC_CAMPO, A_TIPO_CAMPO, A_NOTE_CAMPO, A_ALIAS, A_FLAG_GROUP, I_ORDINE, A_STRQUERY, I_FK_MACROSHOW, I_FK_GRUPPO) VALUES (1, 1, 'T_ANAGRAFICA.NOME', 'NOME', 'varchar', '', 'NOME', 'N', -4, '', -1, -1);
INSERT INTO ER_CAMPI (I_PK_CAMPO, I_FK_TABELLA, A_NOME_CAMPO, A_DESC_CAMPO, A_TIPO_CAMPO, A_NOTE_CAMPO, A_ALIAS, A_FLAG_GROUP, I_ORDINE, A_STRQUERY, I_FK_MACROSHOW, I_FK_GRUPPO) VALUES (2, 1, 'T_ANAGRAFICA.COGNOME', 'COGNOME', 'varchar', '', 'COGNOME', 'N', -3, '', -1, -1);
INSERT INTO ER_CAMPI (I_PK_CAMPO, I_FK_TABELLA, A_NOME_CAMPO, A_DESC_CAMPO, A_TIPO_CAMPO, A_NOTE_CAMPO, A_ALIAS, A_FLAG_GROUP, I_ORDINE, A_STRQUERY, I_FK_MACROSHOW, I_FK_GRUPPO) VALUES (3, 1, 'T_ANAGRAFICA.CODPERSONALE', 'MATRICOLA', 'varchar', '', 'MATRICOLA', 'N', -2, '', -1, -1);
INSERT INTO ER_CAMPI_PROFILI (I_FK_PROFILO, I_FK_MACRO, I_FK_CAMPO) VALUES (4, -1, 1);
DELETE FROM ER_MACRO_TABELLE WHERE I_FK_MACRO = 2
DELETE FROM ER_MACRO_TABELLE WHERE I_FK_MACRO = 1
INSERT INTO ER_MACRO_TABELE (I_FK_MACRO, I_FK_TABELLA, I_ORDINE, A_OBBLIGATORIO) VALUES (1, 1, 1, 'S')
DELETE FROM ER_MACRO_TABELLE WHERE I_FK_MACRO = 1
INSERT INTO ER_MACRO_TABELE (I_FK_MACRO, I_FK_TABELLA, I_ORDINE, A_OBBLIGATORIO) VALUES (1, 1, 1, 'S')
DELETE FROM ER_MACRO_TABELLE WHERE I_FK_MACRO = 1
INSERT INTO ER_MACRO_TABELLE (I_FK_MACRO, I_FK_TABELLA, I_ORDINE, A_OBBLIGATORIO) VALUES (1, 1, 1, 'S')
INSERT INTO ER_MACRO_PROFILI (I_FK_PROFILO, I_FK_MACRO) VALUES (4, 1);
INSERT INTO ER_CAMPI_PROFILI (I_FK_PROFILO, I_FK_MACRO, I_FK_CAMPO) VALUES (4, -1, 2);
INSERT INTO ER_CAMPI_PROFILI (I_FK_PROFILO, I_FK_MACRO, I_FK_CAMPO) VALUES (4, -1, 3);
DELETE FROM ER_MACRO_TABELLE WHERE I_FK_MACRO = 1
INSERT INTO ER_MACRO_TABELLE (I_FK_MACRO, I_FK_TABELLA, I_ORDINE, A_OBBLIGATORIO) VALUES (1, 1, 1, 'S')
INSERT INTO ER_MACRO_TABELLE (I_FK_MACRO, I_FK_TABELLA, I_ORDINE, A_OBBLIGATORIO) VALUES (1, 22, 1, 'S')
INSERT INTO ER_MACRO_TABELLE (I_FK_MACRO, I_FK_TABELLA, I_ORDINE, A_OBBLIGATORIO) VALUES (1, 23, 1, 'N')
INSERT INTO ER_MACRO_TABELLE (I_FK_MACRO, I_FK_TABELLA, I_ORDINE, A_OBBLIGATORIO) VALUES (1, 24, 1, 'N')
INSERT INTO ER_MACRO_TABELLE (I_FK_MACRO, I_FK_TABELLA, I_ORDINE, A_OBBLIGATORIO) VALUES (1, 25, 1, 'N')
INSERT INTO ER_MACRO_TABELLE (I_FK_MACRO, I_FK_TABELLA, I_ORDINE, A_OBBLIGATORIO) VALUES (1, 26, 1, 'N')
INSERT INTO ER_MACRO_TABELLE (I_FK_MACRO, I_FK_TABELLA, I_ORDINE, A_OBBLIGATORIO) VALUES (1, 27, 1, 'N')
INSERT INTO ER_MACRO_TABELLE (I_FK_MACRO, I_FK_TABELLA, I_ORDINE, A_OBBLIGATORIO) VALUES (1, 2, 3, 'N')
INSERT INTO ER_MACRO_TABELLE (I_FK_MACRO, I_FK_TABELLA, I_ORDINE, A_OBBLIGATORIO) VALUES (1, 3, 4, 'N')
INSERT INTO ER_MACRO_TABELLE (I_FK_MACRO, I_FK_TABELLA, I_ORDINE, A_OBBLIGATORIO) VALUES (1, 4, 5, 'N')
INSERT INTO ER_MACRO_TABELLE (I_FK_MACRO, I_FK_TABELLA, I_ORDINE, A_OBBLIGATORIO) VALUES (1, 7, 7, 'N')
INSERT INTO ER_MACRO_TABELLE (I_FK_MACRO, I_FK_TABELLA, I_ORDINE, A_OBBLIGATORIO) VALUES (1, 8, 8, 'N')
INSERT INTO ER_MACRO_TABELLE (I_FK_MACRO, I_FK_TABELLA, I_ORDINE, A_OBBLIGATORIO) VALUES (1, 9, 10, 'N')
INSERT INTO ER_MACRO_TABELLE (I_FK_MACRO, I_FK_TABELLA, I_ORDINE, A_OBBLIGATORIO) VALUES (1, 20, 11, 'N')
INSERT INTO ER_MACRO_TABELLE (I_FK_MACRO, I_FK_TABELLA, I_ORDINE, A_OBBLIGATORIO) VALUES (1, 21, 12, 'N')
INSERT INTO ER_MACRO_TABELLE (I_FK_MACRO, I_FK_TABELLA, I_ORDINE, A_OBBLIGATORIO) VALUES (1, 31, 20, 'N')
INSERT INTO ER_MACRO_TABELLE (I_FK_MACRO, I_FK_TABELLA, I_ORDINE, A_OBBLIGATORIO) VALUES (1, 32, 21, 'N')
INSERT INTO ER_MACRO_TABELLE (I_FK_MACRO, I_FK_TABELLA, I_ORDINE, A_OBBLIGATORIO) VALUES (1, 33, 22, 'N')
INSERT INTO ER_MACRO_TABELLE (I_FK_MACRO, I_FK_TABELLA, I_ORDINE, A_OBBLIGATORIO) VALUES (1, 11, 23, 'N')
INSERT INTO ER_MACRO_TABELLE (I_FK_MACRO, I_FK_TABELLA, I_ORDINE, A_OBBLIGATORIO) VALUES (1, 34, 24, 'N')
DELETE FROM ER_MACRO_TABELLE WHERE I_FK_MACRO = 2
INSERT INTO ER_MACRO_TABELLE (I_FK_MACRO, I_FK_TABELLA, I_ORDINE, A_OBBLIGATORIO) VALUES (2, 1, 1, 'S')
INSERT INTO ER_MACRO_TABELLE (I_FK_MACRO, I_FK_TABELLA, I_ORDINE, A_OBBLIGATORIO) VALUES (2, 5, 3, 'S')
INSERT INTO ER_MACRO_TABELLE (I_FK_MACRO, I_FK_TABELLA, I_ORDINE, A_OBBLIGATORIO) VALUES (2, 6, 4, 'S')
INSERT INTO ER_MACRO_TABELLE (I_FK_MACRO, I_FK_TABELLA, I_ORDINE, A_OBBLIGATORIO) VALUES (2, 28, 5, 'N')
INSERT INTO ER_MACRO_TABELLE (I_FK_MACRO, I_FK_TABELLA, I_ORDINE, A_OBBLIGATORIO) VALUES (2, 29, 6, 'S')
INSERT INTO ER_MACRO_TABELLE (I_FK_MACRO, I_FK_TABELLA, I_ORDINE, A_OBBLIGATORIO) VALUES (2, 30, 7, 'N')
INSERT INTO ER_MACRO_TABELLE (I_FK_MACRO, I_FK_TABELLA, I_ORDINE, A_OBBLIGATORIO) VALUES (2, 35, 8, 'N')
INSERT INTO ER_MACRO_TABELLE (I_FK_MACRO, I_FK_TABELLA, I_ORDINE, A_OBBLIGATORIO) VALUES (2, 37, 11, 'N')
INSERT INTO ER_MACRO_TABELLE (I_FK_MACRO, I_FK_TABELLA, I_ORDINE, A_OBBLIGATORIO) VALUES (2, 38, 30, 'N')
DELETE FROM ER_MACRO_TABELLE WHERE I_FK_MACRO = 3
INSERT INTO ER_MACRO_TABELLE (I_FK_MACRO, I_FK_TABELLA, I_ORDINE, A_OBBLIGATORIO) VALUES (3, 1, 1, 'S')
INSERT INTO ER_MACRO_TABELLE (I_FK_MACRO, I_FK_TABELLA, I_ORDINE, A_OBBLIGATORIO) VALUES (3, 2, 3, 'N')
INSERT INTO ER_MACRO_TABELLE (I_FK_MACRO, I_FK_TABELLA, I_ORDINE, A_OBBLIGATORIO) VALUES (3, 3, 4, 'N')
INSERT INTO ER_MACRO_TABELLE (I_FK_MACRO, I_FK_TABELLA, I_ORDINE, A_OBBLIGATORIO) VALUES (3, 4, 5, 'N')
INSERT INTO ER_MACRO_TABELLE (I_FK_MACRO, I_FK_TABELLA, I_ORDINE, A_OBBLIGATORIO) VALUES (3, 10, 6, 'N')
INSERT INTO ER_MACRO_TABELLE (I_FK_MACRO, I_FK_TABELLA, I_ORDINE, A_OBBLIGATORIO) VALUES (3, 13, 7, 'N')
DELETE FROM ER_MACRO_TABELLE WHERE I_FK_MACRO = 4
INSERT INTO ER_MACRO_TABELLE (I_FK_MACRO, I_FK_TABELLA, I_ORDINE, A_OBBLIGATORIO) VALUES (4, 1, 1, 'S')
INSERT INTO ER_MACRO_TABELLE (I_FK_MACRO, I_FK_TABELLA, I_ORDINE, A_OBBLIGATORIO) VALUES (4, 14, 2, 'S')
INSERT INTO ER_MACRO_TABELLE (I_FK_MACRO, I_FK_TABELLA, I_ORDINE, A_OBBLIGATORIO) VALUES (4, 15, 3, 'N')
DELETE FROM ER_MACRO_TABELLE WHERE I_FK_MACRO = 5
INSERT INTO ER_MACRO_TABELLE (I_FK_MACRO, I_FK_TABELLA, I_ORDINE, A_OBBLIGATORIO) VALUES (5, 1, 1, 'S')
INSERT INTO ER_MACRO_TABELLE (I_FK_MACRO, I_FK_TABELLA, I_ORDINE, A_OBBLIGATORIO) VALUES (5, 17, 2, 'S')
INSERT INTO ER_MACRO_TABELLE (I_FK_MACRO, I_FK_TABELLA, I_ORDINE, A_OBBLIGATORIO) VALUES (5, 18, 3, 'S')
DELETE FROM ER_MACRO_TABELLE WHERE I_FK_MACRO = 6
INSERT INTO ER_MACRO_TABELLE (I_FK_MACRO, I_FK_TABELLA, I_ORDINE, A_OBBLIGATORIO) VALUES (6, 1, 1, 'S')
INSERT INTO ER_MACRO_TABELLE (I_FK_MACRO, I_FK_TABELLA, I_ORDINE, A_OBBLIGATORIO) VALUES (6, 19, 2, 'S')
DELETE FROM ER_MACRO_TABELLE WHERE I_FK_MACRO = 7
INSERT INTO ER_MACRO_TABELLE (I_FK_MACRO, I_FK_TABELLA, I_ORDINE, A_OBBLIGATORIO) VALUES (7, 1, 1, 'S')
INSERT INTO ER_MACRO_TABELLE (I_FK_MACRO, I_FK_TABELLA, I_ORDINE, A_OBBLIGATORIO) VALUES (7, 36, 4, 'N')
INSERT INTO ER_CAMPI (I_PK_CAMPO, I_FK_TABELLA, A_NOME_CAMPO, A_DESC_CAMPO, A_TIPO_CAMPO, A_NOTE_CAMPO, A_ALIAS, A_FLAG_GROUP, I_ORDINE, A_STRQUERY, I_FK_MACROSHOW, I_FK_GRUPPO) VALUES (4, 16, 'T_MONTEORE.A_DATA', 'DATA', 'str_data', '', 'DATA_MONTEORE', 'N', 100, '', -1, -1);
INSERT INTO ER_CAMPI (I_PK_CAMPO, I_FK_TABELLA, A_NOME_CAMPO, A_DESC_CAMPO, A_TIPO_CAMPO, A_NOTE_CAMPO, A_ALIAS, A_FLAG_GROUP, I_ORDINE, A_STRQUERY, I_FK_MACROSHOW, I_FK_GRUPPO) VALUES (5, 11, 'T_SANZIONI.DATA', 'DATA SANZIONE', 'str_data', '', 'DATA_SANZIONE', 'N', 100, '', -1, -1);
INSERT INTO ER_CAMPI (I_PK_CAMPO, I_FK_TABELLA, A_NOME_CAMPO, A_DESC_CAMPO, A_TIPO_CAMPO, A_NOTE_CAMPO, A_ALIAS, A_FLAG_GROUP, I_ORDINE, A_STRQUERY, I_FK_MACROSHOW, I_FK_GRUPPO) VALUES (6, 11, 'T_SANZIONI.NOTE', 'DETTAGLIO SANZIONE', 'varchar', '', 'DETT_SANZIONE', 'N', 100, '', -1, -1);
INSERT INTO ER_CAMPI (I_PK_CAMPO, I_FK_TABELLA, A_NOME_CAMPO, A_DESC_CAMPO, A_TIPO_CAMPO, A_NOTE_CAMPO, A_ALIAS, A_FLAG_GROUP, I_ORDINE, A_STRQUERY, I_FK_MACROSHOW, I_FK_GRUPPO) VALUES (7, 16, 'T_MONTEORE.F_FLESS_GOD', 'FLESSIBILITÀ ORE GODUTE', 'float', '', 'FLESS_GOD', 'N', 100, '', -1, -1);
INSERT INTO ER_CAMPI (I_PK_CAMPO, I_FK_TABELLA, A_NOME_CAMPO, A_DESC_CAMPO, A_TIPO_CAMPO, A_NOTE_CAMPO, A_ALIAS, A_FLAG_GROUP, I_ORDINE, A_STRQUERY, I_FK_MACROSHOW, I_FK_GRUPPO) VALUES (8, 16, 'T_MONTEORE.F_FLESS_MAT', 'FLESSIBILITÀ ORE MATURATE', 'float', '', 'FLESS_MAT', 'N', 100, '', -1, -1);
INSERT INTO ER_CAMPI (I_PK_CAMPO, I_FK_TABELLA, A_NOME_CAMPO, A_DESC_CAMPO, A_TIPO_CAMPO, A_NOTE_CAMPO, A_ALIAS, A_FLAG_GROUP, I_ORDINE, A_STRQUERY, I_FK_MACROSHOW, I_FK_GRUPPO) VALUES (9, 16, 'T_MONTEORE.F_FLESS_RES', 'FLESSIBILITÀ ORE RESIDUE', 'float', '', 'FLESS_RES', 'N', 100, '', -1, -1);
INSERT INTO ER_CAMPI (I_PK_CAMPO, I_FK_TABELLA, A_NOME_CAMPO, A_DESC_CAMPO, A_TIPO_CAMPO, A_NOTE_CAMPO, A_ALIAS, A_FLAG_GROUP, I_ORDINE, A_STRQUERY, I_FK_MACROSHOW, I_FK_GRUPPO) VALUES (10, 16, 'T_MONTEORE.F_FLESS_RAP', 'FLESSIBILITÀ ORE RESIDUE A.P.', 'float', '', 'FLESS_RAP', 'N', 100, '', -1, -1);
INSERT INTO ER_MACRO_PROFILI (I_FK_PROFILO, I_FK_MACRO) VALUES (4, 2);
INSERT INTO ER_MACRO_PROFILI (I_FK_PROFILO, I_FK_MACRO) VALUES (4, 3);
INSERT INTO ER_MACRO_PROFILI (I_FK_PROFILO, I_FK_MACRO) VALUES (4, 4);
INSERT INTO ER_MACRO_PROFILI (I_FK_PROFILO, I_FK_MACRO) VALUES (4, 5);
INSERT INTO ER_MACRO_PROFILI (I_FK_PROFILO, I_FK_MACRO) VALUES (4, 7);
DELETE FROM ER_CAMPI_PROFILI WHERE I_FK_PROFILO = 4 AND I_FK_MACRO = -1 AND I_FK_CAMPO = 1;
DELETE FROM ER_CAMPI_PROFILI WHERE I_FK_PROFILO = 4 AND I_FK_MACRO = -1 AND I_FK_CAMPO = 2;
DELETE FROM ER_CAMPI_PROFILI WHERE I_FK_PROFILO = 4 AND I_FK_MACRO = -1 AND I_FK_CAMPO = 3;
INSERT INTO ER_MACRO_PROFILI (I_FK_PROFILO, I_FK_MACRO) VALUES (4, 6);
INSERT INTO ER_CAMPI_PROFILI (I_FK_PROFILO, I_FK_MACRO, I_FK_CAMPO) VALUES (4, -1, 1);
INSERT INTO ER_CAMPI_PROFILI (I_FK_PROFILO, I_FK_MACRO, I_FK_CAMPO) VALUES (4, -1, 2);
INSERT INTO ER_CAMPI_PROFILI (I_FK_PROFILO, I_FK_MACRO, I_FK_CAMPO) VALUES (4, -1, 3);
INSERT INTO ER_CAMPI_PROFILI (I_FK_PROFILO, I_FK_MACRO, I_FK_CAMPO) VALUES (4, -1, 4);
INSERT INTO ER_CAMPI_PROFILI (I_FK_PROFILO, I_FK_MACRO, I_FK_CAMPO) VALUES (4, -1, 5);
INSERT INTO ER_CAMPI_PROFILI (I_FK_PROFILO, I_FK_MACRO, I_FK_CAMPO) VALUES (4, -1, 6);
INSERT INTO ER_CAMPI_PROFILI (I_FK_PROFILO, I_FK_MACRO, I_FK_CAMPO) VALUES (4, -1, 7);
INSERT INTO ER_CAMPI_PROFILI (I_FK_PROFILO, I_FK_MACRO, I_FK_CAMPO) VALUES (4, -1, 8);
INSERT INTO ER_CAMPI_PROFILI (I_FK_PROFILO, I_FK_MACRO, I_FK_CAMPO) VALUES (4, -1, 9);
INSERT INTO ER_CAMPI_PROFILI (I_FK_PROFILO, I_FK_MACRO, I_FK_CAMPO) VALUES (4, -1, 10);
