INSERT INTO ER_CAMPI (I_PK_CAMPO, I_FK_TABELLA, A_NOME_CAMPO, A_DESC_CAMPO, A_TIPO_CAMPO, A_NOTE_CAMPO, A_ALIAS, A_FLAG_GROUP, I_ORDINE, A_STRQUERY, I_FK_MACROSHOW, I_FK_GRUPPO) VALUES (1, 1, 'T_ANAGRAFICA.NOME', 'NOME', 'varchar', '', 'NOME', 'N', -4, '', -1, -1);
INSERT INTO ER_CAMPI (I_PK_CAMPO, I_FK_TABELLA, A_NOME_CAMPO, A_DESC_CAMPO, A_TIPO_CAMPO, A_NOTE_CAMPO, A_ALIAS, A_FLAG_GROUP, I_ORDINE, A_STRQUERY, I_FK_MACROSHOW, I_FK_GRUPPO) VALUES (2, 1, 'T_ANAGRAFICA.COGNOME', 'COGNOME', 'varchar', '', 'COGNOME', 'N', -3, '', -1, -1);
INSERT INTO ER_CAMPI (I_PK_CAMPO, I_FK_TABELLA, A_NOME_CAMPO, A_DESC_CAMPO, A_TIPO_CAMPO, A_NOTE_CAMPO, A_ALIAS, A_FLAG_GROUP, I_ORDINE, A_STRQUERY, I_FK_MACROSHOW, I_FK_GRUPPO) VALUES (3, 1, 'T_ANAGRAFICA.CODPERSONALE', 'MATRICOLA', 'varchar', '', 'MATRICOLA', 'N', -2, '', -1, -1);
INSERT INTO ER_CAMPI_PROFILI (I_FK_PROFILO, I_FK_MACRO, I_FK_CAMPO) VALUES (4, -1, 1);
DELETE FROM ER_MACRO_TABELLE WHERE I_FK_MACRO = 2
DELETE FROM ER_MACRO_TABELLE WHERE I_FK_MACRO = 1
INSERT INTO ER_MACRO_TABELE (I_FK_MACRO, I_FK_TABELLA, I_ORDINE, A_OBBLIGATORIO) VALUES (1, 1, 1, 'S')
DELETE FROM ER_MACRO_TABELLE WHERE I_FK_MACRO = 1
INSERT INTO ER_MACRO_TABELE (I_FK_MACRO, I_FK_TABELLA, I_ORDINE, A_OBBLIGATORIO) VALUES (1, 1, 1, 'S')
DELETE FROM ER_MACRO_TABELLE WHERE I_FK_MACRO = 1
INSERT INTO ER_MACRO_TABELLE (I_FK_MACRO, I_FK_TABELLA, I_ORDINE, A_OBBLIGATORIO) VALUES (1, 1, 1, 'S')
INSERT INTO ER_MACRO_PROFILI (I_FK_PROFILO, I_FK_MACRO) VALUES (4, 1);
INSERT INTO ER_CAMPI_PROFILI (I_FK_PROFILO, I_FK_MACRO, I_FK_CAMPO) VALUES (4, -1, 2);
INSERT INTO ER_CAMPI_PROFILI (I_FK_PROFILO, I_FK_MACRO, I_FK_CAMPO) VALUES (4, -1, 3);
